/**
 * The image manifest — the ONLY place a path under public/images may appear
 * (CLAUDE.md §8).
 *
 * ⚠️ GENERATED by `node scripts/fetch-images.mjs` from `scripts/image-set.mjs`.
 * Do not hand-edit: the next run overwrites it. Change the set, not the output.
 *
 * All 48 images are **placeholder stock**, self-hosted as WebP at
 * 1600×1200. Nothing is hotlinked — the site makes no request to any image
 * CDN at runtime, which is what lets the cookie policy say no third-party
 * request is made and be telling the truth.
 *
 * The set was chosen against CLAUDE.md §8: one narrow warm family, warm
 * temperature, soft light, no cool tones, no clinical white, **no identifiable
 * face**, no foreign-language product packaging, no before/after. The last three
 * are what rule out most stock "spa" photography.
 *
 * Every entry is `replaceable: true`. When the real shoot happens, this whole
 * file is replaced and no component changes — components take an `id`.
 */
export type ManagedImage = {
  readonly id: string;
  /** Path under /public/images. The only place such a path may be written. */
  readonly src: string;
  /**
   * Turkish, descriptive. Describes THE PHOTOGRAPH, never the premises — the
   * premises have not been photographed, and alt text is not the place to make
   * a claim the copy would not make.
   */
  readonly alt: string;
  readonly width: number;
  readonly height: number;
  readonly credit: string | null;
  /** e.g. 'Unsplash Licence', 'Pexels Licence', 'CC0-1.0'. Never blank. */
  readonly licence: string;
  readonly sourceUrl: string | null;
  /** true for launch stock; false only once real photography lands. */
  readonly replaceable: boolean;
  /** Which surface the image was chosen for. Drives the gallery grouping. */
  readonly group: 'service' | 'blog' | 'page' | 'gallery';
};

export const images: readonly ManagedImage[] = [
  {
    id: 'service-cilt-bakimi',
    src: '/images/services/cilt-bakimi.webp',
    alt: 'Cam tabaklara ayrılmış, farklı yoğunluklarda saydam bakım jelleri.',
    width: 1600,
    height: 1200,
    credit: 'ibnu ihza',
    licence: 'Unsplash Licence',
    sourceUrl:
      'https://unsplash.com/photos/cosmetic-serums-arranged-on-clear-circular-plates-QbHwPe1HE84',
    replaceable: true,
    group: 'service',
  },
  {
    id: 'service-akne-bakimi',
    src: '/images/services/akne-bakimi.webp',
    alt: 'Açık pembe bir yüzeyde yan yana duran üç sabun kalıbı.',
    width: 1600,
    height: 1200,
    credit: 'Nazir Ahmad',
    licence: 'Unsplash Licence',
    sourceUrl:
      'https://unsplash.com/photos/three-different-types-of-soap-on-a-pink-surface-A1gPNi60BlI',
    replaceable: true,
    group: 'service',
  },
  {
    id: 'service-yaslanma-karsiti-bakim',
    src: '/images/services/yaslanma-karsiti-bakim.webp',
    alt: 'Bej bir zeminde yumuşak kıvrımlar oluşturan ışık ve gölge.',
    width: 1600,
    height: 1200,
    credit: 'Pawel Czerwinski',
    licence: 'Unsplash Licence',
    sourceUrl:
      'https://unsplash.com/photos/soft-curved-lines-on-a-beige-background-RpSROCi8iJ8',
    replaceable: true,
    group: 'service',
  },
  {
    id: 'service-leke-bakimi',
    src: '/images/services/leke-bakimi.webp',
    alt: 'Yakın çekimde, dokusu belirgin bej bir yüzey.',
    width: 1600,
    height: 1200,
    credit: 'Stepan Sargsyan',
    licence: 'Unsplash Licence',
    sourceUrl:
      'https://unsplash.com/photos/a-beige-background-with-a-rough-texture-hxk3iYQyjG0',
    replaceable: true,
    group: 'service',
  },
  {
    id: 'service-hassas-cilt-bakimi',
    src: '/images/services/hassas-cilt-bakimi.webp',
    alt: 'Işığı süzen ince keten bir perdenin yakın görünümü.',
    width: 1600,
    height: 1200,
    credit: 'Se. Tsuchiya',
    licence: 'Unsplash Licence',
    sourceUrl:
      'https://unsplash.com/photos/a-close-up-of-a-curtain-with-a-white-background-tfazediSzU8',
    replaceable: true,
    group: 'service',
  },
  {
    id: 'service-kolajen-bakimi',
    src: '/images/services/kolajen-bakimi.webp',
    alt: 'Kıvrılmış sayfaların oluşturduğu katmanlı, krem rengi bir doku.',
    width: 1600,
    height: 1200,
    credit: 'Pawel Czerwinski',
    licence: 'Unsplash Licence',
    sourceUrl:
      'https://unsplash.com/photos/a-close-up-of-a-book-with-curved-pages-TV4yJcHQ6eY',
    replaceable: true,
    group: 'service',
  },
  {
    id: 'service-nemlendirme-bakimi',
    src: '/images/services/nemlendirme-bakimi.webp',
    alt: 'Bej bir yüzeyde bakım şişeleri ve yeşil yapraklar.',
    width: 1600,
    height: 1200,
    credit: 'ibnu ihza',
    licence: 'Unsplash Licence',
    sourceUrl:
      'https://unsplash.com/photos/skincare-products-with-green-leaves-on-a-beige-surface-Z7u2bpbE65Q',
    replaceable: true,
    group: 'service',
  },
  {
    id: 'service-gozenek-sikilastirma',
    src: '/images/services/gozenek-sikilastirma.webp',
    alt: 'Sıcak ışık alan, ince dokulu bir duvar yüzeyi.',
    width: 1600,
    height: 1200,
    credit: 'JKalina',
    licence: 'Unsplash Licence',
    sourceUrl:
      'https://unsplash.com/photos/a-close-up-of-a-wall-with-a-clock-on-it-p2dAyl15BpU',
    replaceable: true,
    group: 'service',
  },
  {
    id: 'service-hucre-yenileme',
    src: '/images/services/hucre-yenileme.webp',
    alt: 'Üst üste binen dalgalı bej katmanlar.',
    width: 1600,
    height: 1200,
    credit: 'Pawel Czerwinski',
    licence: 'Unsplash Licence',
    sourceUrl:
      'https://unsplash.com/photos/stacked-wavy-beige-abstract-layers-EaZ0rkqXr-k',
    replaceable: true,
    group: 'service',
  },
  {
    id: 'service-lazer-epilasyon',
    src: '/images/services/lazer-epilasyon.webp',
    alt: 'Kahverengi ve bej çizgili bir kumaşın yakın çekimi.',
    width: 1600,
    height: 1200,
    credit: 'Kier in Sight Archives',
    licence: 'Unsplash Licence',
    sourceUrl:
      'https://unsplash.com/photos/brown-and-beige-striped-textile-I6Sqy9qh3Iw',
    replaceable: true,
    group: 'service',
  },
  {
    id: 'service-hydrafacial',
    src: '/images/services/hydrafacial.webp',
    alt: 'Ahşap bir tabakta duran damlalıklı şişe ve doğal nesneler.',
    width: 1600,
    height: 1200,
    credit: 'Andrzej Gdula',
    licence: 'Pexels Licence',
    sourceUrl:
      'https://www.pexels.com/photo/natural-oil-in-brown-bottle-laying-on-wooden-plate/',
    replaceable: true,
    group: 'service',
  },
  {
    id: 'service-karbon-peeling',
    src: '/images/services/karbon-peeling.webp',
    alt: 'Duvara yaslanmış kuru çiçekler ve dallar.',
    width: 1600,
    height: 1200,
    credit: 'Peppered Pixels Design Studio',
    licence: 'Unsplash Licence',
    sourceUrl:
      'https://unsplash.com/photos/dry-flowers-and-branches-are-arranged-against-a-wall-Fwvpv1SYeOo',
    replaceable: true,
    group: 'service',
  },
  {
    id: 'service-kimyasal-peeling',
    src: '/images/services/kimyasal-peeling.webp',
    alt: 'Açık zeminde yumuşak, dalgalı çizgiler.',
    width: 1600,
    height: 1200,
    credit: 'Pawel Czerwinski',
    licence: 'Unsplash Licence',
    sourceUrl:
      'https://unsplash.com/photos/a-white-background-with-a-wavy-design-q-3pnV8MKWE',
    replaceable: true,
    group: 'service',
  },
  {
    id: 'service-dermapen',
    src: '/images/services/dermapen.webp',
    alt: 'Yıpranmış bej bir duvarın dokusu.',
    width: 1600,
    height: 1200,
    credit: 'Plato Terentev',
    licence: 'Pexels Licence',
    sourceUrl: 'https://www.pexels.com/photo/beige-and-white-worn-down-wall/',
    replaceable: true,
    group: 'service',
  },
  {
    id: 'service-bb-glow',
    src: '/images/services/bb-glow.webp',
    alt: 'Bej bir zeminde katlanmış, pembe çizgili bir havlu.',
    width: 1600,
    height: 1200,
    credit: 'Karen Laårk Boshoff',
    licence: 'Pexels Licence',
    sourceUrl:
      'https://www.pexels.com/photo/folded-pink-striped-towel-on-beige-surface/',
    replaceable: true,
    group: 'service',
  },
  {
    id: 'service-kalici-makyaj',
    src: '/images/services/kalici-makyaj.webp',
    alt: 'Turuncu bir yüzeyde dağınık duran makyaj fırçaları.',
    width: 1600,
    height: 1200,
    credit: 'Rauf Alvi',
    licence: 'Unsplash Licence',
    sourceUrl:
      'https://unsplash.com/photos/a-group-of-black-pens-sitting-on-top-of-an-orange-surface-vWX9VIl5w-s',
    replaceable: true,
    group: 'service',
  },
  {
    id: 'service-microblading',
    src: '/images/services/microblading.webp',
    alt: 'Etiketsiz kahverengi bir damlalık şişe, ahşap bir yüzeyde.',
    width: 1600,
    height: 1200,
    credit: 'Andrzej Gdula',
    licence: 'Pexels Licence',
    sourceUrl: 'https://www.pexels.com/photo/close-up-of-flask-and-wood/',
    replaceable: true,
    group: 'service',
  },
  {
    id: 'service-kirpik-lifting',
    src: '/images/services/kirpik-lifting.webp',
    alt: 'Yumuşak kıvrımlar yapan bej bir kumaşın yakın çekimi.',
    width: 1600,
    height: 1200,
    credit: 'Kier in Sight Archives',
    licence: 'Unsplash Licence',
    sourceUrl:
      'https://unsplash.com/photos/a-close-up-of-a-piece-of-cloth-kwepwyvPWmM',
    replaceable: true,
    group: 'service',
  },
  {
    id: 'service-kas-tasarimi',
    src: '/images/services/kas-tasarimi.webp',
    alt: 'Ahşap bir masada duran kahverengi dokuma kumaş.',
    width: 1600,
    height: 1200,
    credit: 'Scarbor Siu',
    licence: 'Unsplash Licence',
    sourceUrl:
      'https://unsplash.com/photos/brown-textile-on-brown-wooden-table-LevnxEuhev8',
    replaceable: true,
    group: 'service',
  },
  {
    id: 'service-gelin-bakim-paketi',
    src: '/images/services/gelin-bakim-paketi.webp',
    alt: 'Beyaz kâğıtların yanında duran gül buketi.',
    width: 1600,
    height: 1200,
    credit: 'Pongracz Noemi',
    licence: 'Unsplash Licence',
    sourceUrl:
      'https://unsplash.com/photos/red-rose-bouquet-beside-white-printer-paper-GGdN6qANl5Y',
    replaceable: true,
    group: 'service',
  },
  {
    id: 'blog-cilt-bakimi-rehberi',
    src: '/images/blog/cilt-bakimi-rehberi.webp',
    alt: 'Yuvarlak bir aynanın yanında duran kahverengi cam şişeler ve havlular.',
    width: 1600,
    height: 1200,
    credit: 'Alesia Kozik',
    licence: 'Pexels Licence',
    sourceUrl:
      'https://www.pexels.com/photo/brown-glass-bottles-near-a-round-mirror/',
    replaceable: true,
    group: 'blog',
  },
  {
    id: 'blog-cilt-yenileme-rehberi',
    src: '/images/blog/cilt-yenileme-rehberi.webp',
    alt: 'Beyaz bir kavanozun yanında buğday başakları ve katlanmış havlular.',
    width: 1600,
    height: 1200,
    credit: 'Andrzej Gdula',
    licence: 'Pexels Licence',
    sourceUrl:
      'https://www.pexels.com/photo/wheat-stalks-near-white-container/',
    replaceable: true,
    group: 'blog',
  },
  {
    id: 'blog-epilasyon-rehberi',
    src: '/images/blog/epilasyon-rehberi.webp',
    alt: 'Ahşap raflarda düzgün katlanmış bej tekstiller.',
    width: 1600,
    height: 1200,
    credit: 'Hai Nguyen',
    licence: 'Unsplash Licence',
    sourceUrl:
      'https://unsplash.com/photos/neatly-folded-shirts-stacked-on-wooden-shelves-4JeCx1lZAQQ',
    replaceable: true,
    group: 'blog',
  },
  {
    id: 'blog-cilt-ihtiyaclari',
    src: '/images/blog/cilt-ihtiyaclari.webp',
    alt: 'Seramik tabaklarda turunçgiller ve dokuma bir altlık.',
    width: 1600,
    height: 1200,
    credit: 'Tara Winstead',
    licence: 'Pexels Licence',
    sourceUrl: 'https://www.pexels.com/photo/citrus-fruits-on-the-table/',
    replaceable: true,
    group: 'blog',
  },
  {
    id: 'blog-kas-kirpik-rehberi',
    src: '/images/blog/kas-kirpik-rehberi.webp',
    alt: 'Bej bir fonun önünde kurutulmuş ince dallar.',
    width: 1600,
    height: 1200,
    credit: 'le john',
    licence: 'Pexels Licence',
    sourceUrl: 'https://www.pexels.com/photo/dry-twig-on-beige-background/',
    replaceable: true,
    group: 'blog',
  },
  {
    id: 'blog-ozel-gun-ve-mevsim',
    src: '/images/blog/ozel-gun-ve-mevsim.webp',
    alt: 'Hasır bir sepetin yanında kurutulmuş sarı çiçekler.',
    width: 1600,
    height: 1200,
    credit: 'Marina M',
    licence: 'Pexels Licence',
    sourceUrl:
      'https://www.pexels.com/photo/dried-pycnosorus-flower-on-woven-basket/',
    replaceable: true,
    group: 'blog',
  },
  {
    id: 'page-home-venue',
    src: '/images/pages/home-venue.webp',
    alt: 'Geniş, sıcak tonlu bir karşılama alanı ve oturma grubu.',
    width: 1600,
    height: 1200,
    credit: 'Aalo Lens',
    licence: 'Unsplash Licence',
    sourceUrl:
      'https://unsplash.com/photos/modern-lobby-with-reception-desk-and-seating-area-Ypv0MH4izf8',
    replaceable: true,
    group: 'page',
  },
  {
    id: 'page-home-detail',
    src: '/images/pages/home-detail.webp',
    alt: 'Gün ışığı alan bir köşede bej koltuk ve ahşap sehpada bir mum.',
    width: 1600,
    height: 1200,
    credit: 'Sami Raad',
    licence: 'Pexels Licence',
    sourceUrl:
      'https://www.pexels.com/photo/cozy-living-room-corner-with-armchair-and-candle/',
    replaceable: true,
    group: 'page',
  },
  {
    id: 'page-home-texture',
    src: '/images/pages/home-texture.webp',
    alt: 'Ahşap bir yüzeyin yakın çekimi.',
    width: 1600,
    height: 1200,
    credit: 'Mark Stenglein',
    licence: 'Unsplash Licence',
    sourceUrl:
      'https://unsplash.com/photos/a-close-up-view-of-a-wooden-bench-i6hDsZ-WksU',
    replaceable: true,
    group: 'page',
  },
  {
    id: 'page-about-hero',
    src: '/images/pages/about-hero.webp',
    alt: 'Kavisli ahşap duvarlar ve yuvarlak oturma alanı.',
    width: 1600,
    height: 1200,
    credit: 'Declan Sun',
    licence: 'Unsplash Licence',
    sourceUrl:
      'https://unsplash.com/photos/curved-wooden-walls-with-orange-circular-seating-IIavGesRDcc',
    replaceable: true,
    group: 'page',
  },
  {
    id: 'page-about-space',
    src: '/images/pages/about-space.webp',
    alt: 'Sade döşenmiş, bej tonlarda bir oturma alanı.',
    width: 1600,
    height: 1200,
    credit: 'Thới Nam Cao',
    licence: 'Pexels Licence',
    sourceUrl:
      'https://www.pexels.com/photo/furniture-in-minimalist-interior-design/',
    replaceable: true,
    group: 'page',
  },
  {
    id: 'page-about-detail',
    src: '/images/pages/about-detail.webp',
    alt: 'Ahşap bir rafta duran modern bir lamba ve çerçeveli baskı.',
    width: 1600,
    height: 1200,
    credit: 'Caroline Badran',
    licence: 'Unsplash Licence',
    sourceUrl:
      'https://unsplash.com/photos/modern-lamp-on-a-wooden-shelf-with-art-x2AMuYTZvuM',
    replaceable: true,
    group: 'page',
  },
  {
    id: 'gallery-saksi',
    src: '/images/gallery/saksi.webp',
    alt: 'Ahşap bir kaidede duran saksı bitkisi.',
    width: 1600,
    height: 1200,
    credit: 'Daesun Kim',
    licence: 'Unsplash Licence',
    sourceUrl:
      'https://unsplash.com/photos/a-potted-plant-sitting-on-top-of-a-wooden-block-0mMTS_wGYdk',
    replaceable: true,
    group: 'gallery',
  },
  {
    id: 'gallery-mumlar',
    src: '/images/gallery/mumlar.webp',
    alt: 'Kurutulmuş çiçeklerin iki yanında duran iki mum.',
    width: 1600,
    height: 1200,
    credit: 'mdreza jalali',
    licence: 'Unsplash Licence',
    sourceUrl:
      'https://unsplash.com/photos/two-candles-flank-a-vase-of-dried-flowers-IXPwBIaqEY4',
    replaceable: true,
    group: 'gallery',
  },
  {
    id: 'gallery-eller-dinlenme',
    src: '/images/gallery/eller-dinlenme.webp',
    alt: 'Kucakta dinlenen bir elin yakın çekimi.',
    width: 1600,
    height: 1200,
    credit: 'THLT LCX',
    licence: 'Unsplash Licence',
    sourceUrl:
      'https://unsplash.com/photos/persons-hand-on-persons-lap-ubeslMfS1lk',
    replaceable: true,
    group: 'gallery',
  },
  {
    id: 'gallery-eller-bakim',
    src: '/images/gallery/eller-bakim.webp',
    alt: 'Bakım sırasında yakın çekilmiş eller.',
    width: 1600,
    height: 1200,
    credit: 'Wagner Santos',
    licence: 'Unsplash Licence',
    sourceUrl:
      'https://unsplash.com/photos/persons-hand-on-womans-lap-mBWMvIuVnso',
    replaceable: true,
    group: 'gallery',
  },
  {
    id: 'gallery-beyaz-cicek',
    src: '/images/gallery/beyaz-cicek.webp',
    alt: 'Beyaz çiçeklerin yakın çekimi.',
    width: 1600,
    height: 1200,
    credit: 'Sixteen Miles Out',
    licence: 'Unsplash Licence',
    sourceUrl:
      'https://unsplash.com/photos/a-close-up-of-a-bunch-of-white-flowers-JqYtgeQCtTk',
    replaceable: true,
    group: 'gallery',
  },
  {
    id: 'gallery-yesil-yaprak',
    src: '/images/gallery/yesil-yaprak.webp',
    alt: 'Işığın süzüldüğü bir pencere önünde yeşil yapraklı bir bitki.',
    width: 1600,
    height: 1200,
    credit: 'Yue Iris',
    licence: 'Unsplash Licence',
    sourceUrl: 'https://unsplash.com/photos/green-leafed-plant-Ah7BaPsEsUc',
    replaceable: true,
    group: 'gallery',
  },
  {
    id: 'gallery-kuru-ot',
    src: '/images/gallery/kuru-ot.webp',
    alt: 'Kurutulmuş bej otların yakın çekimi.',
    width: 1600,
    height: 1200,
    credit: 'Katsia Jazwinska',
    licence: 'Unsplash Licence',
    sourceUrl: 'https://unsplash.com/photos/brown-grass-decor-QBqlYTO353w',
    replaceable: true,
    group: 'gallery',
  },
  {
    id: 'gallery-lavabo-ahsap',
    src: '/images/gallery/lavabo-ahsap.webp',
    alt: 'Ahşap ve taşın bir arada kullanıldığı bir lavabo köşesi.',
    width: 1600,
    height: 1200,
    credit: 'Peter Muniz',
    licence: 'Unsplash Licence',
    sourceUrl:
      'https://unsplash.com/photos/modern-bathroom-sink-with-soap-dispenser-and-towel-EwghVOVXmgU',
    replaceable: true,
    group: 'gallery',
  },
  {
    id: 'gallery-kuru-dal',
    src: '/images/gallery/kuru-dal.webp',
    alt: 'Sıcak tonlu bir sıva duvarda dal gölgeleri.',
    width: 1600,
    height: 1200,
    credit: 'Tim Mossholder',
    licence: 'Unsplash Licence',
    sourceUrl:
      'https://unsplash.com/photos/a-black-and-white-photo-of-a-shadow-of-a-tree-Kjy0Q_S_2xg',
    replaceable: true,
    group: 'gallery',
  },
  {
    id: 'gallery-perde-pencere',
    src: '/images/gallery/perde-pencere.webp',
    alt: 'Pencere kenarında ışığı süzen bir perde.',
    width: 1600,
    height: 1200,
    credit: 'the blowup',
    licence: 'Unsplash Licence',
    sourceUrl:
      'https://unsplash.com/photos/a-close-up-of-a-curtain-on-a-window-sill-uY2VYKZRk2Y',
    replaceable: true,
    group: 'gallery',
  },
  {
    id: 'gallery-lavabo-beton',
    src: '/images/gallery/lavabo-beton.webp',
    alt: 'Beton bir lavabo ve mat siyah armatür.',
    width: 1600,
    height: 1200,
    credit: 'Peter Muniz',
    licence: 'Unsplash Licence',
    sourceUrl:
      'https://unsplash.com/photos/modern-bathroom-with-concrete-sink-and-black-faucet-Uq1Sa_lHmSA',
    replaceable: true,
    group: 'gallery',
  },
  {
    id: 'gallery-terrakota-raf',
    src: '/images/gallery/terrakota-raf.webp',
    alt: 'Rustik bir rafta duran terrakota testiler.',
    width: 1600,
    height: 1200,
    credit: 'The Daphne Lens',
    licence: 'Pexels Licence',
    sourceUrl:
      'https://www.pexels.com/photo/rustic-wall-shelf-with-terracotta-vases-and-lamp/',
    replaceable: true,
    group: 'gallery',
  },
  {
    id: 'gallery-serum-bilek',
    src: '/images/gallery/serum-bilek.webp',
    alt: 'Bileğe bakım yağı uygulayan eller.',
    width: 1600,
    height: 1200,
    credit: 'Yaroslav Shuraev',
    licence: 'Pexels Licence',
    sourceUrl: 'https://www.pexels.com/photo/hands-relaxation-girl-blur/',
    replaceable: true,
    group: 'gallery',
  },
  {
    id: 'gallery-kil-testi',
    src: '/images/gallery/kil-testi.webp',
    alt: 'Sıcak ışıkla aydınlatılmış bir nişte duran kil testi.',
    width: 1600,
    height: 1200,
    credit: 'Jan van der Wolf',
    licence: 'Pexels Licence',
    sourceUrl: 'https://www.pexels.com/photo/ancient-clay-jar-on-a-shelf/',
    replaceable: true,
    group: 'gallery',
  },
  {
    id: 'gallery-kil-vazolar',
    src: '/images/gallery/kil-vazolar.webp',
    alt: 'Bir rafta yan yana dizilmiş kil vazolar.',
    width: 1600,
    height: 1200,
    credit: 'ROMAN ODINTSOV',
    licence: 'Pexels Licence',
    sourceUrl: 'https://www.pexels.com/photo/clay-containers-on-shelf/',
    replaceable: true,
    group: 'gallery',
  },
  {
    id: 'gallery-havlular',
    src: '/images/gallery/havlular.webp',
    alt: 'Fayans duvarda çerçeveli bir baskı ve dokulu havlular.',
    width: 1600,
    height: 1200,
    credit: 'Cup of Couple',
    licence: 'Pexels Licence',
    sourceUrl: 'https://www.pexels.com/photo/bathroom-with-mirror-and-drawing/',
    replaceable: true,
    group: 'gallery',
  },
];

const byId = new Map(images.map((image) => [image.id, image]));

/**
 * Resolve an image by id. Throws rather than returning undefined: a missing
 * image is a content bug that should fail the build during static generation,
 * not render a broken box in production.
 */
export function getImage(id: string): ManagedImage {
  const image = byId.get(id);
  if (!image) {
    throw new Error(
      `Unknown image id "${id}". Add it to scripts/image-set.mjs and re-run ` +
        `\`node scripts/fetch-images.mjs\` — components must never reference a ` +
        `path under public/images directly.`,
    );
  }
  return image;
}

/** Every image still awaiting real photography. The swap checklist. */
export function replaceableImages(): readonly ManagedImage[] {
  return images.filter((image) => image.replaceable);
}

/** Images chosen for a given surface, in manifest order. */
export function imagesInGroup(
  group: ManagedImage['group'],
): readonly ManagedImage[] {
  return images.filter((image) => image.group === group);
}

/**
 * Every distinct credit line, for the gallery's attribution block.
 *
 * Neither the Unsplash nor the Pexels licence requires attribution. It is
 * given anyway: it costs one line, it is the courteous reading of both, and it
 * is the only way to find the original of an image later.
 */
export function imageCredits(): readonly {
  readonly credit: string;
  readonly licence: string;
  readonly sourceUrl: string;
}[] {
  const seen = new Map<
    string,
    { credit: string; licence: string; sourceUrl: string }
  >();
  for (const image of images) {
    if (!image.credit || !image.sourceUrl) continue;
    const key = `${image.credit}|${image.licence}`;
    if (!seen.has(key)) {
      seen.set(key, {
        credit: image.credit,
        licence: image.licence,
        sourceUrl: image.sourceUrl,
      });
    }
  }
  return [...seen.values()].sort((a, b) =>
    a.credit.localeCompare(b.credit, 'tr'),
  );
}
