/**
 * Download, crop and convert the launch photography set, then regenerate the
 * image manifest.
 *
 * Reads `scripts/image-set.mjs` — the committed record of what was chosen —
 * writes WebP files under `public/images/`, and writes `src/config/images.ts`
 * from the same data. The manifest is therefore never hand-maintained: the
 * files on disk, the alt text, the credit and the licence cannot drift apart,
 * because there is one source for all four.
 *
 * Everything is **self-hosted**. Nothing is hotlinked: the site makes zero
 * requests to Unsplash or Pexels at runtime, which is also what keeps the
 * cookie policy honest (`content/legal/cerez-politikasi.mdx` claims no
 * third-party request is made, and that has to stay true).
 *
 * Manual tool, run when the set changes. NOT part of `npm run verify` — it hits
 * the network, and its output is committed.
 *
 *   node scripts/fetch-images.mjs [--force]
 */
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import sharp from 'sharp';

import { IMAGE_HEIGHT, IMAGE_SET, IMAGE_WIDTH } from './image-set.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const publicImages = join(root, 'public', 'images');
const force = process.argv.includes('--force');

/**
 * Ask each CDN for a frame comfortably larger than the target, then crop here.
 * Letting the CDN crop would hand the composition to a saliency algorithm; a
 * centre crop of a photograph chosen for its composition is the predictable
 * choice, and `sharp`'s `attention` strategy keeps the subject when the source
 * aspect is far from 4:3.
 */
function sourceUrl(image) {
  const w = IMAGE_WIDTH * 2;
  return image.remote.source === 'unsplash'
    ? `${image.remote.base}?w=${w}&q=85&fm=jpg&fit=max`
    : `${image.remote.base}?auto=compress&cs=srgb&w=${w}`;
}

async function download(url) {
  const response = await fetch(url, {
    headers: { 'User-Agent': 'marenbeauty-image-fetch/1.0' },
  });
  if (!response.ok) throw new Error(`HTTP ${response.status} — ${url}`);
  return Buffer.from(await response.arrayBuffer());
}

/* ── The manifest ─────────────────────────────────────────────────────────── */

const MANIFEST_HEADER = `/**
 * The image manifest — the ONLY place a path under public/images may appear
 * (CLAUDE.md §8).
 *
 * ⚠️ GENERATED by \`node scripts/fetch-images.mjs\` from \`scripts/image-set.mjs\`.
 * Do not hand-edit: the next run overwrites it. Change the set, not the output.
 *
 * All ${IMAGE_SET.length} images are **placeholder stock**, self-hosted as WebP at
 * ${IMAGE_WIDTH}×${IMAGE_HEIGHT}. Nothing is hotlinked — the site makes no request to any image
 * CDN at runtime, which is what lets the cookie policy say no third-party
 * request is made and be telling the truth.
 *
 * The set was chosen against CLAUDE.md §8: one narrow warm family, warm
 * temperature, soft light, no cool tones, no clinical white, **no identifiable
 * face**, no foreign-language product packaging, no before/after. The last three
 * are what rule out most stock "spa" photography.
 *
 * Every entry is \`replaceable: true\`. When the real shoot happens, this whole
 * file is replaced and no component changes — components take an \`id\`.
 */
export type ManagedImage = {
  readonly id: string;
  /** Path under /public/images. The only place such a path may be written. */
  readonly src: string;
  /**
   * Turkish, descriptive. Describes THE PHOTOGRAPH, never the premises — the
   * premises have not been photographed, and alt text is not the place to make
   * a claim the copy would not make.
   */
  readonly alt: string;
  readonly width: number;
  readonly height: number;
  readonly credit: string | null;
  /** e.g. 'Unsplash Licence', 'Pexels Licence', 'CC0-1.0'. Never blank. */
  readonly licence: string;
  readonly sourceUrl: string | null;
  /** true for launch stock; false only once real photography lands. */
  readonly replaceable: boolean;
  /** Which surface the image was chosen for. Drives the gallery grouping. */
  readonly group: 'service' | 'blog' | 'page' | 'gallery';
};
`;

const MANIFEST_FOOTER = `
const byId = new Map(images.map((image) => [image.id, image]));

/**
 * Resolve an image by id. Throws rather than returning undefined: a missing
 * image is a content bug that should fail the build during static generation,
 * not render a broken box in production.
 */
export function getImage(id: string): ManagedImage {
  const image = byId.get(id);
  if (!image) {
    throw new Error(
      \`Unknown image id "\${id}". Add it to scripts/image-set.mjs and re-run \` +
        \`\\\`node scripts/fetch-images.mjs\\\` — components must never reference a \` +
        \`path under public/images directly.\`,
    );
  }
  return image;
}

/** Every image still awaiting real photography. The swap checklist. */
export function replaceableImages(): readonly ManagedImage[] {
  return images.filter((image) => image.replaceable);
}

/** Images chosen for a given surface, in manifest order. */
export function imagesInGroup(
  group: ManagedImage['group'],
): readonly ManagedImage[] {
  return images.filter((image) => image.group === group);
}

/**
 * Every distinct credit line, for the gallery's attribution block.
 *
 * Neither the Unsplash nor the Pexels licence requires attribution. It is
 * given anyway: it costs one line, it is the courteous reading of both, and it
 * is the only way to find the original of an image later.
 */
export function imageCredits(): readonly {
  readonly credit: string;
  readonly licence: string;
  readonly sourceUrl: string;
}[] {
  const seen = new Map<string, { credit: string; licence: string; sourceUrl: string }>();
  for (const image of images) {
    if (!image.credit || !image.sourceUrl) continue;
    const key = \`\${image.credit}|\${image.licence}\`;
    if (!seen.has(key)) {
      seen.set(key, {
        credit: image.credit,
        licence: image.licence,
        sourceUrl: image.sourceUrl,
      });
    }
  }
  return [...seen.values()].sort((a, b) => a.credit.localeCompare(b.credit, 'tr'));
}
`;

function manifestEntry(image) {
  const escape = (value) => value.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
  return `  {
    id: '${escape(image.id)}',
    src: '/images/${image.file}',
    alt: '${escape(image.alt)}',
    width: ${IMAGE_WIDTH},
    height: ${IMAGE_HEIGHT},
    credit: '${escape(image.credit)}',
    licence: '${escape(image.remote.licence)}',
    sourceUrl: '${escape(image.sourceUrl)}',
    replaceable: true,
    group: '${image.group}',
  },`;
}

function writeManifest() {
  const body =
    `\nexport const images: readonly ManagedImage[] = [\n` +
    IMAGE_SET.map(manifestEntry).join('\n') +
    `\n];\n`;

  writeFileSync(
    join(root, 'src', 'config', 'images.ts'),
    MANIFEST_HEADER + body + MANIFEST_FOOTER,
    'utf8',
  );
}

/* ── Run ──────────────────────────────────────────────────────────────────── */

async function main() {
  let fetched = 0;
  let skipped = 0;

  for (const image of IMAGE_SET) {
    const target = join(publicImages, image.file);
    if (existsSync(target) && !force) {
      skipped++;
      continue;
    }

    mkdirSync(dirname(target), { recursive: true });
    const raw = await download(sourceUrl(image));

    await sharp(raw)
      .resize(IMAGE_WIDTH, IMAGE_HEIGHT, {
        fit: 'cover',
        position: sharp.strategy.attention,
      })
      .webp({ quality: 76, effort: 6 })
      .toFile(target);

    fetched++;
    console.log(`  ✓ ${image.file}`);
  }

  writeManifest();

  console.log(
    `\n  ${fetched} downloaded, ${skipped} already present.\n` +
      `  src/config/images.ts regenerated with ${IMAGE_SET.length} entries.\n`,
  );
}

await main();
