/**
 * Licence audit and attribution generator — CLAUDE.md §2, docs/LICENSES.md.
 *
 * Every dependency must carry a licence from the policy list. Anything else
 * needs an explicit, reasoned exception in licenses.exceptions.json.
 *
 * Why a wrapper rather than `license-checker-rseidelsohn --onlyAllow ...`:
 * the raw CLI exits on the FIRST violation and its --excludePackages list is
 * an undocumented semicolon string with no room for a reason. This script
 *   - reports every violation at once,
 *   - understands SPDX expressions ("MIT AND CC-BY-3.0", "MIT OR Apache-2.0"),
 *   - requires a written reason for each exception,
 *   - pins the licence each exception was granted against, so a package that
 *     CHANGES licence fails even though it is excepted,
 *   - reports stale exceptions that are no longer needed,
 *   - REGENERATES the NOTICE attribution file from the real tree and fails if
 *     the committed copy is out of date, so attribution cannot drift.
 *
 * It never widens the policy silently.
 */
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const NOTICE_PATH = join(root, 'NOTICE');

const config = JSON.parse(
  readFileSync(join(root, 'licenses.exceptions.json'), 'utf8'),
);

const policy = new Set(config.policy);
const attributionRequired = new Set(config.attributionRequired ?? []);
const exceptions = new Map(config.exceptions.map((e) => [e.package, e]));

for (const e of config.exceptions) {
  if (!e.reason || !e.licence || !e.scope || !e.status) {
    console.error(
      `\n  ✗ licences: exception for "${e.package}" is missing reason/licence/scope/status.\n`,
    );
    process.exit(1);
  }
}

/**
 * Resolve an SPDX expression against the policy.
 * AND — every term must be allowed. OR — any term suffices.
 * Mixed expressions are not attempted; they fall through to the exception list.
 */
function satisfiesPolicy(expression) {
  const expr = expression.replace(/[()]/g, ' ').trim();
  if (policy.has(expr)) return true;

  if (/\bOR\b/.test(expr) && !/\bAND\b/.test(expr)) {
    return expr.split(/\s+OR\s+/).some((t) => policy.has(t.trim()));
  }
  if (/\bAND\b/.test(expr) && !/\bOR\b/.test(expr)) {
    return expr.split(/\s+AND\s+/).every((t) => policy.has(t.trim()));
  }
  return false;
}

/** Which policy-allowed terms in an expression oblige attribution. */
function attributionTerms(expression) {
  return expression
    .replace(/[()]/g, ' ')
    .split(/\s+(?:AND|OR)\s+/)
    .map((t) => t.trim())
    .filter((t) => attributionRequired.has(t));
}

// Run the checker's JS entry point with the current Node binary. Spawning the
// .bin shim directly is EINVAL on Windows (Node refuses to spawnSync a .cmd).
const checker = join(
  root,
  'node_modules',
  'license-checker-rseidelsohn',
  'bin',
  'license-checker-rseidelsohn.js',
);

const raw = execFileSync(
  process.execPath,
  [checker, '--json', '--excludePrivatePackages'],
  { cwd: root, encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 },
);

const installed = JSON.parse(raw);
const violations = [];
const changed = [];
const used = new Set();
const attributions = [];
const exceptionRecords = [];

for (const [id, meta] of Object.entries(installed)) {
  const licence = String(meta.licenses ?? 'UNKNOWN');
  const name = id.slice(0, id.lastIndexOf('@'));
  const version = id.slice(id.lastIndexOf('@') + 1);

  if (satisfiesPolicy(licence)) {
    const terms = attributionTerms(licence);
    if (terms.length) {
      attributions.push({ name, version, licence, terms, meta });
    }
    continue;
  }

  const exception = exceptions.get(name);
  if (!exception) {
    violations.push({ id, licence });
    continue;
  }

  used.add(name);
  if (exception.licence !== licence) {
    changed.push({ id, was: exception.licence, now: licence });
  }
  exceptionRecords.push({ name, version, licence, exception, meta });
}

const stale = config.exceptions
  .map((e) => e.package)
  .filter((name) => !used.has(name));

// ── NOTICE ──────────────────────────────────────────────────────────────────

function licenceUrl(licence) {
  const first = licence
    .replace(/[()]/g, '')
    .split(/\s+(?:AND|OR)\s+/)[0]
    .trim();
  return `https://spdx.org/licenses/${first}.html`;
}

function readLicenceText(meta) {
  if (!meta.licenseFile || !existsSync(meta.licenseFile)) return null;
  try {
    return readFileSync(meta.licenseFile, 'utf8').trimEnd();
  } catch {
    return null;
  }
}

function buildNotice() {
  const lines = [];
  const rule = '='.repeat(78);

  lines.push(rule);
  lines.push('NOTICE — Maren Beauty');
  lines.push(rule);
  lines.push('');
  lines.push('Third-party attribution for this website.');
  lines.push('');
  lines.push('Generated by scripts/licenses.mjs from the installed dependency');
  lines.push(
    'tree. Do not edit by hand — `npm run licenses` regenerates it and',
  );
  lines.push('fails the build if the committed copy is out of date.');
  lines.push('');
  lines.push('Policy and reasoning: docs/LICENSES.md');
  lines.push('');

  lines.push(rule);
  lines.push('1. ATTRIBUTION-REQUIRED PACKAGES (CC-BY)');
  lines.push(rule);
  lines.push('');
  if (attributions.length === 0) {
    lines.push('None.');
    lines.push('');
  } else {
    lines.push(
      'CC-BY permits reuse but obliges attribution. Each package below',
    );
    lines.push('is credited to its author with a link to its licence.');
    lines.push('');
    for (const a of [...attributions].sort((x, y) =>
      x.name.localeCompare(y.name),
    )) {
      lines.push(`  ${a.name} ${a.version}`);
      lines.push(`      Licence:    ${a.licence}`);
      // Link the term that actually obliges attribution, not merely the first
      // term of the expression — for "(MIT AND CC-BY-3.0)" that is CC-BY-3.0.
      for (const term of a.terms) {
        lines.push(
          `      Attribution: ${term} — https://spdx.org/licenses/${term}.html`,
        );
      }
      lines.push(
        `      Author:     ${a.meta.publisher ?? 'not declared in package metadata'}`,
      );
      if (a.meta.repository)
        lines.push(`      Source:     ${a.meta.repository}`);
      lines.push('');
    }
  }

  lines.push(rule);
  lines.push('2. NAMED LICENCE EXCEPTIONS');
  lines.push(rule);
  lines.push('');
  if (exceptionRecords.length === 0) {
    lines.push('None.');
    lines.push('');
  } else {
    for (const r of [...exceptionRecords].sort((x, y) =>
      x.name.localeCompare(y.name),
    )) {
      lines.push(`  ${r.name} ${r.version}`);
      lines.push(`      Licence:    ${r.licence}`);
      lines.push(`      Licence URL: ${licenceUrl(r.licence)}`);
      lines.push(
        `      Author:     ${r.meta.publisher ?? 'not declared in package metadata'}`,
      );
      if (r.meta.repository)
        lines.push(`      Source:     ${r.meta.repository}`);
      lines.push(`      Scope:      ${r.exception.scope}`);
      lines.push('');
    }
    lines.push(
      '  Under LGPL-3.0, the covered library (libvips, via sharp) is used',
    );
    lines.push(
      '  unmodified and dynamically linked. Recipients may replace it with',
    );
    lines.push('  a modified version; nothing here obstructs that.');
    lines.push('');
  }

  const embedded = exceptionRecords
    .filter((r) => r.exception.embedLicenceText)
    .sort((x, y) => x.name.localeCompare(y.name));

  if (embedded.length) {
    lines.push(rule);
    lines.push('3. FULL LICENCE TEXTS');
    lines.push(rule);
    lines.push('');
    for (const r of embedded) {
      const text = readLicenceText(r.meta);
      lines.push('-'.repeat(78));
      lines.push(`${r.name} — ${r.licence}`);
      lines.push('-'.repeat(78));
      lines.push('');
      lines.push(
        text ??
          `Licence text not bundled with the package. See ${licenceUrl(r.licence)}`,
      );
      lines.push('');
    }
  }

  return lines.join('\n').replace(/\s+$/, '') + '\n';
}

const notice = buildNotice();
const existingNotice = existsSync(NOTICE_PATH)
  ? readFileSync(NOTICE_PATH, 'utf8')
  : null;
const noticeStale = existingNotice !== notice;
if (noticeStale) writeFileSync(NOTICE_PATH, notice, 'utf8');

// ── Report ──────────────────────────────────────────────────────────────────

const total = Object.keys(installed).length;
console.log(`\n  licences: ${total} packages audited.`);
console.log(`  policy: ${config.policy.join(', ')}`);
console.log(
  `  named exceptions: ${config.exceptions.length}   attribution entries: ${attributions.length}\n`,
);

let failed = false;

if (violations.length) {
  failed = true;
  console.error(`  ✗ ${violations.length} package(s) outside the policy with`);
  console.error(`    no recorded exception:\n`);
  for (const v of violations) {
    console.error(`      ${v.licence.padEnd(40)} ${v.id}`);
  }
  console.error(
    `\n    Add a reasoned entry to licenses.exceptions.json, or remove the`,
  );
  console.error(
    `    dependency. Do not widen "policy" without owner sign-off.\n`,
  );
}

if (changed.length) {
  failed = true;
  console.error(`  ✗ ${changed.length} excepted package(s) CHANGED LICENCE:\n`);
  for (const c of changed) {
    console.error(`      ${c.id}: granted for ${c.was}, now ${c.now}`);
  }
  console.error(`\n    Re-review the exception before updating it.\n`);
}

if (stale.length) {
  console.warn(`  ⚠ ${stale.length} exception(s) no longer needed:\n`);
  for (const s of stale) console.warn(`      ${s}`);
  console.warn(`\n    Remove them from licenses.exceptions.json.\n`);
}

const pending = config.exceptions.filter(
  (e) => e.status !== 'approved' && used.has(e.package),
);
if (pending.length) {
  console.warn(`  ⚠ ${pending.length} exception(s) AWAITING OWNER APPROVAL:\n`);
  for (const p of pending) {
    console.warn(`      ${p.licence.padEnd(34)} ${p.package}  (${p.scope})`);
  }
  console.warn(`\n    See docs/LICENSES.md §5.\n`);
}

if (noticeStale) {
  failed = true;
  console.error(`  ✗ NOTICE was out of date and has been regenerated.`);
  console.error(
    `    Attribution must match the real tree — commit the new NOTICE.\n`,
  );
}

if (exceptionRecords.length) {
  console.log(`  named exceptions in tree (all approved):`);
  for (const r of exceptionRecords.sort((a, b) =>
    a.name.localeCompare(b.name),
  )) {
    // Version included: the same package can legitimately appear more than once
    // at different versions, and without it that reads as an error.
    console.log(
      `      ${r.licence.padEnd(40)} ${r.name}@${r.version}  (${r.exception.scope})`,
    );
  }
  console.log('');
}

if (failed) process.exit(1);
console.log(`  ✓ licences: policy satisfied, NOTICE current.\n`);
