import { existsSync, readFileSync, readdirSync, statSync } from 'node:fs';
import { join, sep } from 'node:path';

import sharp from 'sharp';
import { describe, expect, it } from 'vitest';

import {
  IMAGE_SET,
  IMAGE_HEIGHT,
  IMAGE_WIDTH,
} from '../../scripts/image-set.mjs';
import { BLOG_CATEGORIES } from '@/content-layer';
import {
  getImage,
  images,
  imagesInGroup,
  replaceableImages,
} from '@/config/images';
import { supportingImageIds } from '@/config/services';
import { getAllServices } from '@/content-layer';

const ROOT = process.cwd();
const filePath = (src: string) => join(ROOT, 'public', src);

/* ── The set itself ───────────────────────────────────────────────────────── */

describe('the launch image set', { timeout: 60_000 }, () => {
  it('ships 48 images, every id and every path unique', () => {
    expect(images).toHaveLength(48);
    expect(new Set(images.map((i) => i.id)).size).toBe(images.length);
    expect(new Set(images.map((i) => i.src)).size).toBe(images.length);
  });

  it('is generated from scripts/image-set.mjs, not hand-maintained', () => {
    // If the two ever disagree, the manifest was edited by hand and the next
    // `node scripts/fetch-images.mjs` would silently revert the edit.
    expect(images.map((i) => i.id)).toEqual(IMAGE_SET.map((i) => i.id));
    expect(readFileSync(join(ROOT, 'src/config/images.ts'), 'utf8')).toContain(
      'GENERATED by',
    );
  });

  it('every manifest entry has a file on disk', () => {
    for (const image of images) {
      expect(existsSync(filePath(image.src)), image.src).toBe(true);
    }
  });

  /**
   * The strongest check here: the DECLARED dimensions are read back out of the
   * shipped file. `width`/`height` are what reserve layout, so a manifest that
   * disagrees with the file is a CLS bug that nothing else would catch.
   */
  it('every file is WebP at exactly the declared size', async () => {
    for (const image of images) {
      const meta = await sharp(filePath(image.src)).metadata();
      expect(meta.format, image.src).toBe('webp');
      expect(meta.width, image.src).toBe(image.width);
      expect(meta.height, image.src).toBe(image.height);
      expect(image.width).toBe(IMAGE_WIDTH);
      expect(image.height).toBe(IMAGE_HEIGHT);
    }
  });

  it('ships no orphan file under public/images', () => {
    const declared = new Set(images.map((i) => filePath(i.src)));
    const onDisk: string[] = [];
    const walk = (dir: string) => {
      for (const entry of readdirSync(dir)) {
        const full = join(dir, entry);
        if (statSync(full).isDirectory()) walk(full);
        else if (full.endsWith('.webp')) onDisk.push(full);
      }
    };
    walk(join(ROOT, 'public', 'images'));

    const orphans = onDisk.filter((f) => !declared.has(f));
    expect(orphans.map((f) => f.split(sep).join('/'))).toEqual([]);
  });

  it('keeps the whole set under 8 MB', () => {
    const bytes = images.reduce(
      (total, image) => total + statSync(filePath(image.src)).size,
      0,
    );
    expect(bytes).toBeLessThan(8 * 1024 * 1024);
  });
});

/* ── The visual family, measured rather than asserted ─────────────────────── */

// Decoding 48 WebP files twice takes longer than vitest's 5s default. The
// answer is a longer timeout, not a smaller sample: a family check that skips
// images is not a family check.
describe('one narrow warm family', { timeout: 60_000 }, () => {
  /**
   * `CLAUDE.md` §8 asks for warm temperature, soft light, no cool tones and no
   * clinical white. Those are judgements — but two of them have an arithmetic
   * shadow, and this measures it on the ACTUAL SHIPPED PIXELS rather than
   * trusting the selection process. A future swap that drops in a cool grey
   * frame fails here.
   *
   * Bounds are set with headroom below the real set (min warmth 18.7, luminance
   * 0.30–0.81), so ordinary variation passes and a genuine outlier does not.
   */
  it('every image is warm: mean red exceeds mean blue', async () => {
    for (const image of images) {
      const stats = await sharp(filePath(image.src)).stats();
      const [r, , b] = stats.channels.map((c) => c.mean);
      expect(r! - b!, `${image.id} is not warm enough`).toBeGreaterThan(12);
    }
  });

  it('no image is a black frame or blown-out clinical white', async () => {
    for (const image of images) {
      const stats = await sharp(filePath(image.src)).stats();
      const [r, g, b] = stats.channels.map((c) => c.mean);
      const luminance = (0.299 * r! + 0.587 * g! + 0.114 * b!) / 255;
      expect(luminance, image.id).toBeGreaterThan(0.22);
      expect(luminance, image.id).toBeLessThan(0.88);
    }
  });
});

/* ── Licensing and attribution ────────────────────────────────────────────── */

describe('licensing', () => {
  it('uses only the two free licences', () => {
    for (const image of images) {
      expect(['Unsplash Licence', 'Pexels Licence'], image.id).toContain(
        image.licence,
      );
    }
  });

  /**
   * `plus.unsplash.com/premium_photo-…` is Unsplash+, a paid subscription with
   * different terms. It looks identical in a search result and would be a
   * licence violation in the manifest, so the source table is checked directly.
   */
  it('contains no Unsplash+ photograph', () => {
    const source = readFileSync(join(ROOT, 'scripts/image-set.mjs'), 'utf8');
    expect(source).not.toContain('premium_photo');
    expect(source).not.toContain('plus.unsplash.com');
  });

  it('credits every photographer and links a resolvable source', () => {
    for (const image of images) {
      expect(image.credit, image.id).toBeTruthy();
      expect(image.sourceUrl, image.id).toMatch(
        /^https:\/\/(unsplash\.com|www\.pexels\.com)\//,
      );
    }
  });

  /**
   * The manifest keeps `credit`, `licence` and `sourceUrl`; the site renders
   * none of them (G30). The assertion above pins the record, this one pins the
   * absence of the machinery that used to publish it — an exported helper is
   * how it would quietly come back.
   */
  it('exports no helper that formats credits for display', async () => {
    const manifest = await import('@/config/images');
    expect(Object.keys(manifest)).not.toContain('imageCredits');
  });

  it('marks the whole set replaceable', () => {
    expect(replaceableImages()).toHaveLength(images.length);
  });
});

/* ── Self-hosting ─────────────────────────────────────────────────────────── */

describe('self-hosting', () => {
  /**
   * The cookie policy states that the site makes no third-party request. A
   * hotlinked image would make that false — and would be the exact kind of
   * quiet drift between the legal text and the implementation that M12 built
   * tests to prevent.
   */
  it('hotlinks nothing: no image CDN host appears anywhere in src/', () => {
    const offenders: string[] = [];
    const walk = (dir: string) => {
      for (const entry of readdirSync(dir)) {
        const full = join(dir, entry);
        if (statSync(full).isDirectory()) walk(full);
        else if (/\.(ts|tsx|css)$/.test(full)) {
          const text = readFileSync(full, 'utf8');
          if (/images\.(unsplash|pexels)\.com/.test(text)) offenders.push(full);
        }
      }
    };
    walk(join(ROOT, 'src'));
    expect(offenders).toEqual([]);
  });

  it('configures no remote image pattern in next.config.ts', () => {
    const config = readFileSync(join(ROOT, 'next.config.ts'), 'utf8');
    expect(config).not.toMatch(/remotePatterns|domains:/);
  });
});

/* ── Coverage: every surface that needs an image has one ──────────────────── */

describe('coverage', () => {
  it('gives all 20 services a hero that resolves', () => {
    const services = getAllServices();
    expect(services).toHaveLength(20);
    for (const service of services) {
      const image = getImage(service.heroImageId);
      expect(image.group, service.slug).toBe('service');
    }
  });

  it('gives all six blog categories a hero', () => {
    for (const category of BLOG_CATEGORIES) {
      const image = getImage(`blog-${category}`);
      expect(image.group, category).toBe('blog');
    }
  });

  it('has a page image for the home and about surfaces', () => {
    const ids = imagesInGroup('page').map((i) => i.id);
    expect(ids).toContain('page-home-venue');
    expect(ids).toContain('page-about-hero');
    expect(ids).toContain('page-about-space');
    expect(ids).toContain('page-about-detail');
  });

  it('throws on an unknown id rather than rendering a broken box', () => {
    expect(() => getImage('yok-boyle-bir-gorsel')).toThrow(/Unknown image id/);
  });
});

/* ── Supporting imagery ───────────────────────────────────────────────────── */

describe('supporting images on service pages', () => {
  const services = getAllServices();

  it('gives every service two supporting frames, and never its own hero', () => {
    for (const service of services) {
      const supporting = supportingImageIds(service.slug);
      expect(supporting, service.slug).toHaveLength(2);
      expect(supporting, service.slug).not.toContain(service.heroImageId);
      expect(new Set(supporting).size, service.slug).toBe(2);
      for (const id of supporting) {
        expect(getImage(id).group).toBe('gallery');
      }
    }
  });

  it('is deterministic — the same slug always gets the same frames', () => {
    expect(supportingImageIds('hydrafacial')).toEqual(
      supportingImageIds('hydrafacial'),
    );
    expect(supportingImageIds('hydrafacial')).not.toEqual(
      supportingImageIds('dermapen'),
    );
  });

  it('spreads across the pool rather than reusing two favourites', () => {
    const used = new Set(
      services.flatMap((service) => supportingImageIds(service.slug)),
    );
    expect(used.size).toBeGreaterThan(8);
  });
});
