import { readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';

import { describe, expect, it } from 'vitest';

import { logoTreatments } from '@/config/logo';

/**
 * The logo set, and the promises that make it a logo rather than a picture of
 * one.
 *
 * `public/brand/**` and `src/config/logo.ts` are both generated by
 * `node scripts/build-logo.mjs` from the same source. They are checked against
 * each other here for the same reason the image manifest is: two generated
 * artefacts that nothing compares will drift the first time somebody edits one
 * by hand, and the drift is invisible until a stale mark ships.
 */

const ROOT = process.cwd();
const BRAND = join(ROOT, 'public', 'brand');
const LOCKUPS = ['monogram', 'monogram-32', 'stacked', 'horizontal'] as const;

const svg = (treatment: string, lockup: string) =>
  readFileSync(join(BRAND, treatment, `${lockup}.svg`), 'utf8');

describe('the logo set', () => {
  it('ships every lockup for every treatment, and nothing else', () => {
    expect(Object.keys(logoTreatments).sort()).toEqual([
      'arch',
      'seal',
      'serif',
    ]);

    for (const treatment of Object.keys(logoTreatments)) {
      expect(readdirSync(join(BRAND, treatment)).sort()).toEqual(
        LOCKUPS.map((l) => `${l}.svg`).sort(),
      );
    }
  });

  it('has not drifted from the generated module', () => {
    for (const [key, treatment] of Object.entries(logoTreatments)) {
      for (const lockup of LOCKUPS) {
        const file = svg(key, lockup);
        const { viewBox, parts } = treatment.lockups[lockup];

        expect(file, `${key}/${lockup} viewBox`).toContain(
          `viewBox="${viewBox}"`,
        );
        for (const part of parts) {
          expect(file, `${key}/${lockup} path`).toContain(`d="${part.d}"`);
        }
        // Same number of paths in both, so a part cannot be dropped from one.
        expect(
          (file.match(/<path/g) ?? []).length,
          `${key}/${lockup} path count`,
        ).toBe(parts.length);
      }
    }
  });

  /**
   * The reason every letter is path data rather than `<text>`: a favicon, an
   * Instagram avatar and a print PDF all render with no webfont available, and
   * `<text>` in those contexts silently falls back to something that is not
   * Fraunces.
   */
  it('outlines all text — no <text>, no font-family, anywhere', () => {
    for (const treatment of Object.keys(logoTreatments)) {
      for (const lockup of LOCKUPS) {
        const file = svg(treatment, lockup);
        expect(file, `${treatment}/${lockup}`).not.toMatch(
          /<text|font-family/i,
        );
      }
    }
  });

  /**
   * One flat colour, inherited. A baked-in hex would make the inverse colourway
   * impossible to set from CSS, which is the whole requirement: the same file
   * has to work on ivory and on espresso.
   */
  it('carries no colour of its own — one flat currentColor', () => {
    for (const treatment of Object.keys(logoTreatments)) {
      for (const lockup of LOCKUPS) {
        const file = svg(treatment, lockup);
        expect(file, `${treatment}/${lockup}`).not.toMatch(
          /#[0-9a-f]{3,8}\b|rgb\(|hsl\(|oklch\(/i,
        );
        expect(file, `${treatment}/${lockup}`).toContain('currentColor');
        // No gradients, no filters, no shadows — the brief, and also the only
        // way a mark survives being printed in one ink.
        expect(file, `${treatment}/${lockup}`).not.toMatch(
          /Gradient|<filter|drop-shadow|opacity=/i,
        );
      }
    }
  });

  it('names itself for a screen reader', () => {
    for (const treatment of Object.keys(logoTreatments)) {
      for (const lockup of LOCKUPS) {
        const file = svg(treatment, lockup);
        expect(file, `${treatment}/${lockup}`).toContain('role="img"');
        expect(file, `${treatment}/${lockup}`).toMatch(/<title>[^<]+<\/title>/);
      }
    }
  });

  /**
   * The 32px form is allowed to differ from the display form, and for the serif
   * it MUST: its engraver's rule lands under a pixel at that size and reads as
   * a grey smear beneath the letter. Simplifying is the instruction; shipping
   * the smudge is not.
   */
  it('drops the serif rule at 32px rather than shipping it sub-pixel', () => {
    const serif = logoTreatments.serif.lockups;
    expect(serif.monogram.parts).toHaveLength(2); // letter + rule
    expect(serif['monogram-32'].parts).toHaveLength(1); // letter alone
  });

  it('keeps the other two treatments whole at 32px', () => {
    // Nothing is dropped — they are only weighted up, which is a different
    // thing and worth being able to see in the diff.
    for (const key of ['arch', 'seal'] as const) {
      const lockups = logoTreatments[key].lockups;
      expect(lockups['monogram-32'].parts).toHaveLength(
        lockups.monogram.parts.length,
      );
      expect(lockups['monogram-32'].parts[0]!.d).not.toBe(
        lockups.monogram.parts[0]!.d,
      );
    }
  });

  it('is not wired into the site yet', () => {
    // The owner picks a treatment first. The only importer is the dev-only
    // styleguide; when one is chosen this assertion is what needs updating,
    // deliberately.
    const importers: string[] = [];
    const walk = (dir: string) => {
      for (const entry of readdirSync(dir, { withFileTypes: true })) {
        const full = join(dir, entry.name);
        if (entry.isDirectory()) walk(full);
        else if (/\.tsx?$/.test(entry.name)) {
          if (/from '@\/config\/logo'/.test(readFileSync(full, 'utf8'))) {
            importers.push(
              full.replace(/.*src[\\/]/, 'src/').replace(/\\/g, '/'),
            );
          }
        }
      }
    };
    walk(join(ROOT, 'src'));
    expect(importers).toEqual(['src/app/styleguide/page.tsx']);
  });
});
